name: Run Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress cache
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run

      - name: Merge Mochawesome JSON reports
        run: npx mochawesome-merge cypress/reports/*.json > mochawesome.json

      - name: Generate Mochawesome HTML report
        run: npx marge mochawesome.json --reportDir cypress/html-report

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/html-report